In [3]:
import pandas as pd

In [4]:
# Create Series, Custom indexing, provide series name
marks = [1,2,3,4,5,6]
sub = ['a', 'b', 'c', 'd', 'e', 'f']

ser = pd.Series(marks, index=sub, name='Chirag Mark')
ser

a    1
b    2
c    3
d    4
e    5
f    6
Name: Chirag Mark, dtype: int64

In [5]:
# Use Dictionery

marks = {
    'a' : 1,
    'b' : 2,
    'c' : 3,
}
ser = pd.Series(marks)
ser

a    1
b    2
c    3
dtype: int64

In [16]:
subs = pd.read_csv('/content/subs.csv')

In [20]:
runs = pd.read_csv('/content/kohli_ipl.csv', index_col='match_no')

In [18]:
movies = pd.read_csv('/content/bollywood.csv', index_col='movie')

In [22]:
runs.sort_values('runs')

          runs
match_no
8            0
87           0
93           0
91           0
206          0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       206, 207, 208, 209, 210, 211, 212, 213, 214, 215],
      dtype='int64', name='match_no', length=215)

In [35]:
x = pd.Series([1,2,3,4,5])

x[0]

np.int64(1)

In [40]:
runs[5:6]

          runs
match_no
6            9

In [42]:
movies[-5:-1]

                                    lead
movie
Hum Tumhare Hain Sanam    Shah Rukh Khan
Aankhen (2002 film)     Amitabh Bachchan
Saathiya (film)             Vivek Oberoi
Company (film)                Ajay Devgn

In [54]:
runs.iloc[0]

runs    1
Name: 1, dtype: int64

In [52]:
movies.iloc[0]

lead    Vicky Kaushal
Name: Uri: The Surgical Strike, dtype: object

In [63]:
ser[0] = 6

ser

/tmp/ipykernel_1605/2282362933.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  ser[0] = 6

a    6
b    2
c    3
dtype: int64

In [65]:
ser['sst'] = 123

ser

a        6
b        2
c        3
sst    123
dtype: int64

In [74]:
runs.loc[[2,3,4]]

runs

          runs
match_no
1          100
2          100
3          100
4          100
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [75]:
100+runs

          runs
match_no
1          200
2          200
3          200
4          200
5          101
...        ...
211        100
212        120
213        173
214        125
215        107

[215 rows x 1 columns]

In [76]:
movies.value_counts()

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Naveen Bawa          1
Naushaad Abbas       1
Nauheed Cyrusi       1
Natalia Janoszek     1
Nishikant Kamat      1
Name: count, Length: 566, dtype: int64

In [77]:
import sys
sys.getsizeof(runs)

11768

In [83]:
runs.dtypes

runs    int64
dtype: object

In [87]:
sys.getsizeof(runs.astype('int64'))

11768

In [88]:
11768-10908

860

In [89]:
movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [92]:
movies.drop_duplicates()

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Sssshhh...                            Tanishaa Mukerji
Rules: Pyaar Ka Superhit Formula                Tanuja
Right Here Right Now (film)                      Ankit
Talaash: The Hunt Begins...              Rakhee Gulzar
The Pink Mirror                        Edwin Fernandes

[566 rows x 1 columns]