In [3]:
import pandas as pd
import numpy as np

In [6]:
ipl = pd.read_csv('/content/deliveries.csv')
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0.0,4.0,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2.0,2.0,NaN,NaN,NaN

In [7]:
movies = pd.read_csv('/content/imdb-top-1000.csv')
movies.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [8]:
movies.groupby('Genre')['Gross'].sum().sort_values(ascending=False).head(3)

Genre
Drama     3.540997e+10
Action    3.263226e+10
Comedy    1.566387e+10
Name: Gross, dtype: float64

In [9]:
movies.groupby('Genre')['IMDB_Rating'].mean().sort_values(ascending=False).head(1)

Genre
Western    8.35
Name: IMDB_Rating, dtype: float64

In [10]:
movies.groupby('Director')['No_of_Votes'].sum().sort_values(ascending=False)

Director
Christopher Nolan    11578345
Quentin Tarantino     8123208
Steven Spielberg      7817166
David Fincher         6607859
Martin Scorsese       6513530
                       ...
J. Lee Thompson         26457
Peter Mullan            25938
René Laloux             25229
Francis Lee             25198
Kaige Chen              25088
Name: No_of_Votes, Length: 548, dtype: int64

In [11]:
movies.groupby('Genre')[['IMDB_Rating','Series_Title']].max()['Series_Title']

Genre
Action                                   Yôjinbô
Adventure                             Zombieland
Animation            Ôkami kodomo no Ame to Yuki
Biography                                Zerkalo
Comedy                  Zindagi Na Milegi Dobara
Crime                          À bout de souffle
Drama                                  Zwartboek
Family       Willy Wonka & the Chocolate Factory
Fantasy                                Nosferatu
Film-Noir                          The Third Man
Horror                                 The Thing
Mystery                                  Vertigo
Thriller                         Wait Until Dark
Western                   The Outlaw Josey Wales
Name: Series_Title, dtype: object

In [12]:
movies.groupby('Genre').get_group('Horror')

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
49,Psycho,1960,109,Horror,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
75,Alien,1979,117,Horror,8.4,Ridley Scott,Sigourney Weaver,787806,78900000.0,89.0
271,The Thing,1982,109,Horror,8.1,John Carpenter,Kurt Russell,371271,13782838.0,57.0
419,The Exorcist,1973,122,Horror,8.0,William Friedkin,Ellen Burstyn,362393,232906145.0,81.0
544,Night of the Living Dead,1968,96,Horror,7.9,George A. Romero,Duane Jones,116557,89029.0,89.0
707,The Innocents,1961,100,Horror,7.8,Jack Clayton,Deborah Kerr,27007,2616000.0,88.0
724,Get Out,2017,104,Horror,7.7,Jordan Peele,Daniel Kaluuya,492851,176040665.0,85.0
844,Halloween,1978,91,Horror,7.7,John Carpenter,Donald Pleasence,233106,47000000.0,87.0
876,The Invisible Man,1933,71,Horror,7.7,James Whale,Claude Rains,30683,298791505.0,87.0
932,Saw,2004,103,Horror,7.6,James Wan,Cary Elwes,379020,56000369.0,46.0
948,The Others,2001,101,Horror,7.6,Alejandro Amenábar,Nicole Kidman,337651,96522687.0,74.0

In [13]:
genres = movies.groupby('Genre')

def rank_movie(group):
  group['genre_rank'] = group['IMDB_Rating'].rank(ascending=False)
  return group

genres.apply(rank_movie, include_groups=False)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime  IMDB_Rating           Director              Star1  \
Genre
Action   2        152          9.0  Christopher Nolan     Christian Bale
         5        201          8.9      Peter Jackson        Elijah Wood
         8        148          8.8  Christopher Nolan  Leonardo DiCaprio
         10       178          8.8      Peter Jackson        Elijah Wood
         13       179          8.7      Peter Jackson        Elijah Wood
...               ...          ...                ...                ...
Thriller 700      108          7.8      Terence Young     Audrey Hepburn
Western  12       161          8.8       Sergio Leone     Clint Eastwood
         48       165          8.5       Sergio Leone        Henry Fonda
         115      132          8.3       Sergio Leone     Clint Eastwood
         691      135          7.8     Clint Eastwood     Clint Eastwood

              No_of_Votes        Gross  Metascore  genre_rank
Genre
Action   2        2303232  534858444.0       84.0         1.0
         5        1642758  377845905.0       94.0         2.0
         8        2067042  292576195.0       74.0         3.5
         10       1661481  315544750.0       92.0         3.5
         13       1485555  342551365.0       87.0         6.0
...                   ...          ...        ...         ...
Thriller 700        27733   17550741.0       81.0         1.0
Western  12        688390    6100000.0       90.0         1.0
         48        302844    5321508.0       80.0         2.0
         115       232772   15000000.0       74.0         3.0
         691        65659   31800000.0       69.0         4.0

[1000 rows x 10 columns]

In [14]:
def normal(group):
  group['normalise'] = (group['IMDB_Rating']-group['IMDB_Rating'].min())/(group['IMDB_Rating'].max() - group['IMDB_Rating'].min())
  return group

genres.apply(normal)

/tmp/ipykernel_14962/220535707.py:5: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  genres.apply(normal)

                                                   Series_Title Released_Year  \
Genre
Action   2                                      The Dark Knight          2008
         5        The Lord of the Rings: The Return of the King          2003
         8                                            Inception          2010
         10   The Lord of the Rings: The Fellowship of the Ring          2001
         13               The Lord of the Rings: The Two Towers          2002
...                                                         ...           ...
Thriller 700                                    Wait Until Dark          1967
Western  12                     Il buono, il brutto, il cattivo          1966
         48                        Once Upon a Time in the West          1968
         115                         Per qualche dollaro in più          1965
         691                             The Outlaw Josey Wales          1976

              Runtime     Genre  IMDB_Rating           Director  \
Genre
Action   2        152    Action          9.0  Christopher Nolan
         5        201    Action          8.9      Peter Jackson
         8        148    Action          8.8  Christopher Nolan
         10       178    Action          8.8      Peter Jackson
         13       179    Action          8.7      Peter Jackson
...               ...       ...          ...                ...
Thriller 700      108  Thriller          7.8      Terence Young
Western  12       161   Western          8.8       Sergio Leone
         48       165   Western          8.5       Sergio Leone
         115      132   Western          8.3       Sergio Leone
         691      135   Western          7.8     Clint Eastwood

                          Star1  No_of_Votes        Gross  Metascore  \
Genre
Action   2       Christian Bale      2303232  534858444.0       84.0
         5          Elijah Wood      1642758  377845905.0       94.0
         8    Leonardo DiCaprio      2067042  292576195.0       74.0
         10         Elijah Wood      1661481  315544750.0       92.0
         13         Elijah Wood      1485555  342551365.0       87.0
...                         ...          ...          ...        ...
Thriller 700     Audrey Hepburn        27733   17550741.0       81.0
Western  12      Clint Eastwood       688390    6100000.0       90.0
         48         Henry Fonda       302844    5321508.0       80.0
         115     Clint Eastwood       232772   15000000.0       74.0
         691     Clint Eastwood        65659   31800000.0       69.0

              normalise
Genre
Action   2     1.000000
         5     0.928571
         8     0.857143
         10    0.857143
         13    0.785714
...                 ...
Thriller 700        NaN
Western  12    1.000000
         48    0.700000
         115   0.500000
         691   0.000000

[1000 rows x 11 columns]

In [15]:
ipl.head()

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0.0,4.0,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0.0,0.0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2.0,2.0,NaN,NaN,NaN

In [36]:
six = ipl[ipl['batsman_runs'] == 6]
six.groupby('batsman')['batsman'].count().sort_values(ascending=False)
# ipl.groupby('batsman')[ipl['batsman_runs'] == 6].sum().sort_values(ascending=False).head(1)

batsman
CH Gayle       187
SK Raina       124
RG Sharma      116
YK Pathan       97
MS Dhoni        94
              ...
T Kohli          1
A Mithun         1
A Nehra          1
A Choudhary      1
Z Khan           1
Name: batsman, Length: 271, dtype: int64

In [40]:
mask1 = ipl[ipl['over'] > 15]
mask2 = mask1[(mask1['batsman_runs'] == 4) | (mask1['batsman_runs'] == 6)]
mask2.groupby('batsman')['batsman'].count().sort_values(ascending=False)

batsman
MS Dhoni          163
RG Sharma         134
KA Pollard        101
AB de Villiers     96
V Kohli            83
                 ...
Shoaib Malik        1
TG Southee          1
T Taibu             1
Sunny Singh         1
TS Mills            1
Name: batsman, Length: 289, dtype: int64

In [45]:
ipl.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batsman', 'non_striker', 'bowler', 'is_super_over', 'wide_runs',
       'bye_runs', 'legbye_runs', 'noball_runs', 'penalty_runs',
       'batsman_runs', 'extra_runs', 'total_runs', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='object')

In [60]:
# mask1 = ipl[(ipl['batting_team'] == 'Royal Challengers Bangalore') & (ipl['batsman'] == 'V Kohli')]
mask2 = ipl.groupby(['batting_team','batsman'])
mask2.get_group(('Royal Challengers Bangalore','V Kohli'))['total_runs'].sum()

np.float64(2507.0)

In [66]:
import pandas as pd

# Load dataset
df = pd.read_csv("deliveries.csv")

# Filter only Virat Kohli's batting data
kohli_df = df[df['batsman'] == 'V Kohli']

# Group by opponent team (bowling team)
grouped = kohli_df.groupby('bowling_team')

# Calculate stats
grouped.agg(
    matches=('match_id', 'nunique'),
    innings=('match_id', 'count'),
    runs=('batsman_runs', 'sum'),
    balls=('ball', 'count'),
    fours=('batsman_runs', lambda x: (x == 4).sum()),
    sixes=('batsman_runs', lambda x: (x == 6).sum())
)

# # Calculate strike rate
# result['strike_rate'] = (result['runs'] / result['balls']) * 100

# # Sort by runs
# result = result.sort_values(by='runs', ascending=False)

# print(result)

                         matches  innings  runs  balls  fours  sixes
bowling_team
Chennai Super Kings           23      616   749    616     57     30
Deccan Chargers               10      230   306    230     23     14
Delhi Capitals                 2       50    66     50      3      3
Delhi Daredevils              18      553   763    553     74     22
Gujarat Lions                  5      186   283    186     24     11
Kings XI Punjab               23      495   636    495     74     18
Kochi Tuskers Kerala           2       52    50     52      7      0
Kolkata Knight Riders         21      515   675    515     58     22
Mumbai Indians                24      497   628    497     52     24
Pune Warriors                  5      101   128    101      9      5
Rajasthan Royals              19      351   370    351     29     10
Rising Pune Supergiant         2       67    83     67      7      2
Rising Pune Supergiants        2      128   188    128     15      9
Sunrisers Hyderabad           13      370   509    370     50     21

In [72]:
# Create a function that can return the highest score of any batsman

def highest_score(batsman):
  mask = ipl[ipl['batsman'] == batsman]
  return mask.groupby('match_id')['batsman_runs'].sum().sort_values(ascending=False).head(1)

highest_score('V Kohli')

match_id
432    93
Name: batsman_runs, dtype: int64