In [3]:
import pandas as pd
import numpy as np

In [4]:
courses = pd.read_csv('/content/courses.csv')
students = pd.read_csv('/content/students.csv')
nov = pd.read_csv('/content/reg-month1.csv')
dec = pd.read_csv('/content/reg-month2.csv')
matches = pd.read_csv('/content/matches.csv')
delivery = pd.read_csv('/content/deliveries.csv')

In [5]:
courses

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

In [6]:
students

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
19          20       Hanuman Hegde       11
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2

In [7]:
nov

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [8]:
dec

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [9]:
matches

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [10]:
delivery

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0.0,0.0,0.0,0.0,4.0,0.0,4.0,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0.0,0.0,0.0,0.0,0.0,2.0,2.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41299,176,1,Mumbai Indians,Rajasthan Royals,14,4,AT Rayudu,SS Tiwary,YK Pathan,0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,NaN,NaN,NaN
41300,176,1,Mumbai Indians,Rajasthan Royals,14,5,SS Tiwary,AT Rayudu,YK Pathan,0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,NaN,NaN,NaN
41301,176,1,Mumbai Indians,Rajasthan Royals,14,6,AT Rayudu,SS Tiwary,YK Pathan,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
41302,176,1,Mumbai Indians,Rajasthan Royals,15,1,SS Tiwary,AT Rayudu,AA Jhunjhunwala,0,...,0.0,0.0,0.0,0.0,4.0,0.0,4.0,NaN,NaN,NaN
41303,176,1,Mumbai Indians,Rajasthan Royals,15,2,SS Tiwary,AT Rayudu,AA Jhunjhunwala,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
#Concatenating
regs = pd.concat([nov, dec], ignore_index=True)
regs

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [12]:
multi = pd.concat([nov, dec], keys=['Nov','Dec'])
multi

        student_id  course_id
Nov 0           23          1
    1           15          5
    2           18          6
    3           23          4
    4           16          9
    5           18          1
    6            1          1
    7            7          8
    8           22          3
    9           15          1
    10          19          4
    11           1          6
    12           7         10
    13          11          7
    14          13          3
    15          24          4
    16          21          1
    17          16          5
    18          23          3
    19          17          7
    20          23          6
    21          25          1
    22          19          2
    23          25         10
    24           3          3
Dec 0            3          5
    1           16          7
    2           12         10
    3           12          1
    4           14          9
    5            7          7
    6            7          2
    7           16          3
    8           17         10
    9           11          8
    10          14          6
    11          12          5
    12          12          7
    13          18          8
    14           1         10
    15           1          9
    16           2          5
    17           7          6
    18          22          5
    19          22          6
    20          23          9
    21          23          5
    22          14          4
    23          14          1
    24          11         10
    25          42          9
    26          50          8
    27          38          1

In [16]:
total = regs.merge(courses, how='inner', on='course_id')['price'].sum()
total

np.int64(154247)

In [21]:
multi.reset_index().merge(courses, how='inner', on='course_id').groupby('level_0')['price'].sum()

level_0
Dec    65072
Nov    89175
Name: price, dtype: int64

In [24]:
regs.merge(students, on='student_id').merge(courses, on='course_id')[['name', 'course_name', 'price']]

                  name       course_name  price
0       Chhavi Lachman            python   2499
1            Preet Sha           tableau   2499
2      Fardeen Mahabir          power bi   1899
3       Chhavi Lachman  machine learning   9999
4         Elias Dodiya            plotly    699
5      Fardeen Mahabir            python   2499
6        Kailash Harjo            python   2499
7         Tarun Thaker            pandas   1099
8           Yash Sethi     data analysis   4999
9            Preet Sha            python   2499
10        Qabeel Raman  machine learning   9999
11       Kailash Harjo          power bi   1899
12        Tarun Thaker           pyspark   2499
13  David Mukhopadhyay          ms sxcel   1599
14      Munni Varghese     data analysis   4999
15        Radhika Suri  machine learning   9999
16          Seema Kota            python   2499
17        Elias Dodiya           tableau   2499
18      Chhavi Lachman     data analysis   4999
19        Yasmin Palan          ms sxcel   1599
20      Chhavi Lachman          power bi   1899
21     Shashank D’Alia            python   2499
22        Qabeel Raman               sql   3499
23     Shashank D’Alia           pyspark   2499
24      Parveen Bhalla     data analysis   4999
25      Parveen Bhalla           tableau   2499
26        Elias Dodiya          ms sxcel   1599
27          Radha Dutt           pyspark   2499
28          Radha Dutt            python   2499
29    Pranab Natarajan            plotly    699
30        Tarun Thaker          ms sxcel   1599
31        Tarun Thaker               sql   3499
32        Elias Dodiya     data analysis   4999
33        Yasmin Palan           pyspark   2499
34  David Mukhopadhyay            pandas   1099
35    Pranab Natarajan          power bi   1899
36          Radha Dutt           tableau   2499
37          Radha Dutt          ms sxcel   1599
38     Fardeen Mahabir            pandas   1099
39       Kailash Harjo           pyspark   2499
40       Kailash Harjo            plotly    699
41         Esha Butala           tableau   2499
42        Tarun Thaker          power bi   1899
43          Yash Sethi           tableau   2499
44          Yash Sethi          power bi   1899
45      Chhavi Lachman            plotly    699
46      Chhavi Lachman           tableau   2499
47    Pranab Natarajan  machine learning   9999
48    Pranab Natarajan            python   2499
49  David Mukhopadhyay           pyspark   2499

In [32]:
nov.merge(dec, on='student_id').merge(students, on='student_id')['name'].unique()

array(['Chhavi Lachman', 'Fardeen Mahabir', 'Elias Dodiya',
       'Kailash Harjo', 'Tarun Thaker', 'Yash Sethi',
       'David Mukhopadhyay', 'Yasmin Palan', 'Parveen Bhalla'],
      dtype=object)

In [36]:
common_student_id = np.intersect1d(nov['student_id'], dec['student_id'])
students[students['student_id'].isin(common_student_id)]

    student_id                name  partner
0            1       Kailash Harjo       23
2            3      Parveen Bhalla        3
6            7        Tarun Thaker        9
10          11  David Mukhopadhyay       20
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18

In [42]:
# courses['course_id']
# regs['course_id']
course_id_list = np.setdiff1d(courses['course_id'], regs['course_id'])
courses[courses['course_id'].isin(course_id_list)]

    course_id course_name  price
10         11       Numpy    699
11         12         C++   1299

In [45]:
students.merge(students, how='inner', left_on='partner', right_on='student_id')[['name_x', 'name_y']]

                name_x              name_y
0        Kailash Harjo      Chhavi Lachman
1          Esha Butala       Kailash Harjo
2       Parveen Bhalla      Parveen Bhalla
3          Marlo Dugal    Pranab Natarajan
4          Kusum Bahri  Lakshmi Contractor
5   Lakshmi Contractor      Aayushman Sant
6         Tarun Thaker   Nitika Chatterjee
7       Radheshyam Dey         Kusum Bahri
8    Nitika Chatterjee         Marlo Dugal
9       Aayushman Sant      Radheshyam Dey
10  David Mukhopadhyay       Hanuman Hegde
11          Radha Dutt        Qabeel Raman
12      Munni Varghese        Radhika Suri
13    Pranab Natarajan          Yash Sethi
14           Preet Sha        Elias Dodiya
15        Elias Dodiya     Shashank D’Alia
16        Yasmin Palan        Tarun Thaker
17     Fardeen Mahabir      Munni Varghese
18        Qabeel Raman          Radha Dutt
19       Hanuman Hegde  David Mukhopadhyay
20          Seema Kota           Preet Sha
21          Yash Sethi          Seema Kota
22      Chhavi Lachman     Fardeen Mahabir
23        Radhika Suri        Yasmin Palan
24     Shashank D’Alia         Esha Butala

In [53]:
regs.merge(students, on='student_id').groupby(['student_id','name'])['course_id'].nunique().sort_values(ascending=False).head(3)

student_id  name
23          Chhavi Lachman      6
7           Tarun Thaker        5
14          Pranab Natarajan    4
Name: course_id, dtype: int64

In [54]:
regs.merge(students, on='student_id').merge(courses, on='course_id').groupby(['student_id','name'])['price'].sum().sort_values(ascending=False).head(3)

student_id  name
23          Chhavi Lachman      22594
14          Pranab Natarajan    15096
19          Qabeel Raman        13498
Name: price, dtype: int64

In [57]:
delivery.head(1)

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

In [66]:
delivery.shape

(41304, 21)

In [63]:
matches.shape

(636, 18)

In [64]:
matches.head(1)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN

In [73]:
matches.merge(delivery, left_on='id', right_on='match_id').groupby('venue').agg({'batsman_runs': lambda x: (x==6).count()}).sort_values('batsman_runs', ascending=False).head(3)

                                           batsman_runs
venue
Kingsmead                                          3643
Rajiv Gandhi International Stadium, Uppal          3623
M Chinnaswamy Stadium                              3409

In [74]:
temp_df = delivery.merge(matches, left_on='match_id', right_on='id')

In [83]:
six_df = temp_df[temp_df['batsman_runs'] == 6]

In [85]:
num_six = six_df.groupby('venue')['venue'].count()

In [90]:
num_matches = matches['venue'].value_counts()

In [91]:
(num_six/num_matches).sort_values(ascending=False).head(3)

venue
Holkar Cricket Stadium    12.000000
De Beers Diamond Oval     11.333333
SuperSport Park           10.000000
dtype: float64

In [94]:
temp_df.groupby(['season', 'batsman'])['batsman_runs'].sum().reset_index().sort_values('batsman_runs', ascending=False).drop_duplicates(subset=['season'], keep='first')

     season     batsman  batsman_runs
358    2017   DA Warner         641.0
115    2008    SE Marsh         616.0
229    2009   ML Hayden         572.0
306    2010  AD Mathews          65.0